version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.51.0
    ports:
      - "16686:16686" # Jaeger UI frontend
      - "4317:4317"   # gRPC port for accepts traces in OpenTelemetry OTLP format
      - "4318:4318"   # HTTP port for accepts traces in OpenTelemetry OTLP format
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  ydb:
    image: ydbplatform/local-ydb:latest
    hostname: localhost
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
      - "5432:5432"
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - YDB_TABLE_ENABLE_PREPARED_DDL=true
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_FEATURE_FLAGS=enable_topic_service_tx
      - YDB_ENABLE_COLUMN_TABLES=true
